[package]
name = "fractals"
version = "0.1.0"
edition = "2024"

[dependencies]
beryllium = "0.13.3"
bytemuck = "1.25.1"
image = "0.25.10"
noise = "0.9.0"
ogl33 = { version = "0.2", features = ["debug_error_checks"] }
pollster = "1.0.1"
queues = "1.1.0"
rand = "0.10.2"
web-time = "1.1.0"
wgpu = "30.0.0"
winit = "0.30.13"
